env: DB=postgres
language: node_js
# there is a problem with npm 5.3.0 which will cause the tests to fail
install: "npm install -g npm@5.2.0 && npm install coffee-script && npm install && ./node_modules/.bin/cake install"
# ensure our application is compiled before we run our tests
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "8.2.1"
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - contact@stevemcarthur.co.uk
